In [49]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score , precision_score , recall_score , f1_score
import joblib

['scaler.pkl']

In [50]:
df = pd.read_csv("Iris.csv")

In [51]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [52]:
df.shape

(150, 6)

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [54]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [73]:
df.isnull().sum()

SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [76]:
df = df.drop(columns=["Id"], errors="ignore")

print(df.columns)

Index(['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [81]:

X = df.drop("Species" , axis=1)
y=df["Species"]

print(X)
print(y)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]
0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [78]:
X_train , X_test , y_train , y_test = train_test_split (
    X , y , test_size = 0.2 , random_state = 42 
)
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [79]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [80]:
# train knn

knn = KNeighborsClassifier()
knn.fit(X_train_scaled , y_train)

KNeighborsClassifier()

In [70]:
# KNN performance

y_pred_knn = knn.predict(X_test_scaled)

print("accuracy_score:",accuracy_score(y_test , y_pred_knn))
print("precision_score:",precision_score(y_test , y_pred_knn,average='weighted'))
print("recall_score:",recall_score(y_test , y_pred_knn,average='macro'))
print("F1_score:",f1_score(y_test , y_pred_knn,average='macro'))

accuracy_score: 1.0
precision_score: 1.0
recall_score: 1.0
F1_score: 1.0

In [71]:
# train logistic regression

log_reg = LogisticRegression()
log_reg.fit(X_train_scaled , y_train)

LogisticRegression()

In [72]:
y_pred_log_reg = log_reg.predict(X_test_scaled)



print("accuracy_score:",accuracy_score(y_test , y_pred_log_reg))
print("precision_score:",precision_score(y_test , y_pred_log_reg,average='weighted'))
print("recall_score:",recall_score(y_test , y_pred_log_reg,average='macro'))
print("F1_score:",f1_score(y_test , y_pred_log_reg,average='macro'))

accuracy_score: 1.0
precision_score: 1.0
recall_score: 1.0
F1_score: 1.0

In [63]:
# train naive bayes


nb = GaussianNB()
nb.fit(X_train_scaled , y_train)

GaussianNB()

In [64]:
y_pred_nb = nb.predict(X_test_scaled)

print("accuracy_score:",accuracy_score(y_test , y_pred_nb))
print("precision_score:",precision_score(y_test , y_pred_nb,average='weighted'))
print("recall_score:",recall_score(y_test , y_pred_nb,average='macro'))
print("F1_score:",f1_score(y_test , y_pred_nb,average='macro'))

accuracy_score: 1.0
precision_score: 1.0
recall_score: 1.0
F1_score: 1.0

In [65]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    "n_neighbors": [3, 5, 7, 9]
}

grid = GridSearchCV(
    KNeighborsClassifier(),
    param_grid,
    cv=5
)

grid.fit(X, y)

print(grid.best_params_)
print(grid.best_score_ * 100)

{'n_neighbors': 3}
87.33333333333333

In [82]:
import joblib 
joblib.dump(knn , "iris_model.pkl") 
joblib.dump(scaler , "scaler.pkl")  
df = df.drop(columns=["Id"], errors="ignore")